image: Visual Studio 2017
configuration: Static
platform: x86
before_build:
- cmd: git submodule update --init
build:
  verbosity: minimal
artifacts:
- path: Static\*
  name: MabinogiResource.$(GitVersion_LegacySemVerPadded)
  type: zip
