version: 1.0.8.{build}
max_jobs: 2
image: Visual Studio 2019
before_build:
- cmd: git submodule update --init
build:
  project: MabinogiResource.sln
  verbosity: minimal
artifacts:
- path: Static\*
  name: MabinogiResource.$(GitVersion_LegacySemVerPadded)
  type: zip
